import type { Employee, Department, Position } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const departments: Department[] = [
  { id: 'd1', name: 'Engineering' },
  { id: 'd2', name: 'Design' },
  { id: 'd3', name: 'Marketing' },
  { id: 'd4', name: 'Sales' },
  { id: 'd5', name: 'Human Resources' },
];

export const positions: Position[] = [
  { id: 'p1', name: 'Software Engineer' },
  { id: 'p2', name: 'UX/UI Designer' },
  { id: 'p3', name: 'Product Manager' },
  { id: 'p4', name: 'Marketing Specialist' },
  { id: 'p5', name: 'Sales Representative' },
  { id: 'p6', name: 'HR Manager' },
  { id: 'p7', name: 'Frontend Developer' },
  { id: 'p8', name: 'Backend Developer' },
];

export const employees: Employee[] = [
  {
    id: 'emp1',
    name: 'Lora Piterson',
    email: 'lora.piterson@vrs.com',
    avatarUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
    position: positions[1],
    department: departments[1],
    role: 'EMPLOYEE',
    status: 'Active',
  },
  {
    id: 'emp2',
    name: 'Harry Bender',
    email: 'harry.bender@vrs.com',
    avatarUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
    position: positions[0],
    department: departments[0],
    role: 'MANAGER',
    status: 'Active',
  },
  {
    id: 'emp3',
    name: 'Jonathan Kelly',
    email: 'jonathan.kelly@vrs.com',
    avatarUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
    position: positions[7],
    department: departments[0],
    role: 'EMPLOYEE',
    status: 'Active',
  },
  {
    id: 'emp4',
    name: 'Billie Wright',
    email: 'billie.wright@vrs.com',
    avatarUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
    position: positions[3],
    department: departments[2],
    role: 'EMPLOYEE',
    status: 'On Leave',
  },
  {
    id: 'emp5',
    name: 'Sarah Page',
    email: 'sarah.page@vrs.com',
    avatarUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
    position: positions[4],
    department: departments[3],
    role: 'EMPLOYEE',
    status: 'Active',
  },
  {
    id: 'emp6',
    name: 'Erica Wyatt',
    email: 'erica.wyatt@vrs.com',
    avatarUrl: PlaceHolderImages[5].imageUrl,
    imageHint: PlaceHolderImages[5].imageHint,
    position: positions[5],
    department: departments[4],
    role: 'HR_ADMIN',
    status: 'Active',
  },
  {
    id: 'emp7',
    name: 'Alex Chen',
    email: 'alex.chen@vrs.com',
    avatarUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
    position: positions[6],
    department: departments[0],
    role: 'EMPLOYEE',
    status: 'Active',
  },
    {
    id: 'emp8',
    name: 'Maria Garcia',
    email: 'maria.garcia@vrs.com',
    avatarUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
    position: positions[2],
    department: departments[0],
    role: 'MANAGER',
    status: 'Inactive',
  },
];
